/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTrackVisitRouteImport } from './routes/api/track/visit'
import { Route as ApiTrackDownloadRouteImport } from './routes/api/track/download'
import { Route as ApiTrackAccessRequestRouteImport } from './routes/api/track/access-request'
import { Route as ApiAdminVisitsRouteImport } from './routes/api/admin/visits'
import { Route as ApiAdminSessionRouteImport } from './routes/api/admin/session'
import { Route as ApiAdminOrdersRouteImport } from './routes/api/admin/orders'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminDownloadsRouteImport } from './routes/api/admin/downloads'
import { Route as ApiAdminDashboardRouteImport } from './routes/api/admin/dashboard'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackVisitRoute = ApiTrackVisitRouteImport.update({
  id: '/api/track/visit',
  path: '/api/track/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackDownloadRoute = ApiTrackDownloadRouteImport.update({
  id: '/api/track/download',
  path: '/api/track/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackAccessRequestRoute = ApiTrackAccessRequestRouteImport.update({
  id: '/api/track/access-request',
  path: '/api/track/access-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminVisitsRoute = ApiAdminVisitsRouteImport.update({
  id: '/api/admin/visits',
  path: '/api/admin/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSessionRoute = ApiAdminSessionRouteImport.update({
  id: '/api/admin/session',
  path: '/api/admin/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrdersRoute = ApiAdminOrdersRouteImport.update({
  id: '/api/admin/orders',
  path: '/api/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDownloadsRoute = ApiAdminDownloadsRouteImport.update({
  id: '/api/admin/downloads',
  path: '/api/admin/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDashboardRoute = ApiAdminDashboardRouteImport.update({
  id: '/api/admin/dashboard',
  path: '/api/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/downloads': typeof ApiAdminDownloadsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/orders': typeof ApiAdminOrdersRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/visits': typeof ApiAdminVisitsRoute
  '/api/track/access-request': typeof ApiTrackAccessRequestRoute
  '/api/track/download': typeof ApiTrackDownloadRoute
  '/api/track/visit': typeof ApiTrackVisitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/downloads': typeof ApiAdminDownloadsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/orders': typeof ApiAdminOrdersRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/visits': typeof ApiAdminVisitsRoute
  '/api/track/access-request': typeof ApiTrackAccessRequestRoute
  '/api/track/download': typeof ApiTrackDownloadRoute
  '/api/track/visit': typeof ApiTrackVisitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/downloads': typeof ApiAdminDownloadsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/orders': typeof ApiAdminOrdersRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/visits': typeof ApiAdminVisitsRoute
  '/api/track/access-request': typeof ApiTrackAccessRequestRoute
  '/api/track/download': typeof ApiTrackDownloadRoute
  '/api/track/visit': typeof ApiTrackVisitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api/admin/dashboard'
    | '/api/admin/downloads'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/orders'
    | '/api/admin/session'
    | '/api/admin/visits'
    | '/api/track/access-request'
    | '/api/track/download'
    | '/api/track/visit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api/admin/dashboard'
    | '/api/admin/downloads'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/orders'
    | '/api/admin/session'
    | '/api/admin/visits'
    | '/api/track/access-request'
    | '/api/track/download'
    | '/api/track/visit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/admin/dashboard'
    | '/api/admin/downloads'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/orders'
    | '/api/admin/session'
    | '/api/admin/visits'
    | '/api/track/access-request'
    | '/api/track/download'
    | '/api/track/visit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiAdminDashboardRoute: typeof ApiAdminDashboardRoute
  ApiAdminDownloadsRoute: typeof ApiAdminDownloadsRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminOrdersRoute: typeof ApiAdminOrdersRoute
  ApiAdminSessionRoute: typeof ApiAdminSessionRoute
  ApiAdminVisitsRoute: typeof ApiAdminVisitsRoute
  ApiTrackAccessRequestRoute: typeof ApiTrackAccessRequestRoute
  ApiTrackDownloadRoute: typeof ApiTrackDownloadRoute
  ApiTrackVisitRoute: typeof ApiTrackVisitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track/visit': {
      id: '/api/track/visit'
      path: '/api/track/visit'
      fullPath: '/api/track/visit'
      preLoaderRoute: typeof ApiTrackVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track/download': {
      id: '/api/track/download'
      path: '/api/track/download'
      fullPath: '/api/track/download'
      preLoaderRoute: typeof ApiTrackDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track/access-request': {
      id: '/api/track/access-request'
      path: '/api/track/access-request'
      fullPath: '/api/track/access-request'
      preLoaderRoute: typeof ApiTrackAccessRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/visits': {
      id: '/api/admin/visits'
      path: '/api/admin/visits'
      fullPath: '/api/admin/visits'
      preLoaderRoute: typeof ApiAdminVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/session': {
      id: '/api/admin/session'
      path: '/api/admin/session'
      fullPath: '/api/admin/session'
      preLoaderRoute: typeof ApiAdminSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/orders': {
      id: '/api/admin/orders'
      path: '/api/admin/orders'
      fullPath: '/api/admin/orders'
      preLoaderRoute: typeof ApiAdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/downloads': {
      id: '/api/admin/downloads'
      path: '/api/admin/downloads'
      fullPath: '/api/admin/downloads'
      preLoaderRoute: typeof ApiAdminDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/dashboard': {
      id: '/api/admin/dashboard'
      path: '/api/admin/dashboard'
      fullPath: '/api/admin/dashboard'
      preLoaderRoute: typeof ApiAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiAdminDashboardRoute: ApiAdminDashboardRoute,
  ApiAdminDownloadsRoute: ApiAdminDownloadsRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminOrdersRoute: ApiAdminOrdersRoute,
  ApiAdminSessionRoute: ApiAdminSessionRoute,
  ApiAdminVisitsRoute: ApiAdminVisitsRoute,
  ApiTrackAccessRequestRoute: ApiTrackAccessRequestRoute,
  ApiTrackDownloadRoute: ApiTrackDownloadRoute,
  ApiTrackVisitRoute: ApiTrackVisitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
